name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ejecutar cuando se haga push a la rama main
  workflow_dispatch: # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'airdrop-app/package-lock.json'

      - name: Install Dependencies 📦
        run: |
          cd airdrop-app
          npm ci # Instalación limpia basada en package-lock.json

      - name: Build 🔧
        run: |
          cd airdrop-app
          npm run build
          # Asegurarse de que CNAME esté presente
          cp public/CNAME build/
        env:
          CI: false # Evita que la compilación falle por advertencias

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: airdrop-app/build # Carpeta que contiene los archivos compilados
          branch: gh-pages # Rama donde se desplegará
          clean: true # Limpia los archivos existentes en la rama gh-pages 